---
  - name: Playbook
    hosts: webservers
    become: yes
    become_user: root
    tasks:
      - name: ensure apache is at the latest version
        yum:
          name: apache2
          state: latest
      - name: ensure apache is running
        service:
          name: apache2
          state: started
---
- name: playbook2
  hosts: all
  become: yes
  tasks:
    - name: this file is for sample
      apt:
        name: apache2
        state: latest
   - name: besure apache2 is running
     service:
       name: apache2
       state: started
       added
       deleted
